import Head from 'next/head';
import FootballDataInput from './FootballDataInput';
import { useState } from 'react';

export default function Home() {
  const [currentText, setCurrentText] = useState('');

  function handleCommentaryRequest() {
    console.log('Commentary requested for: ' + currentText);
  }

  const onTextChange = (e) => {
    setCurrentText(e.target.value);
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <FootballDataInput
        text={currentText}
        onCommentaryRequested={() => handleCommentaryRequest()}
        onTextChange={onTextChange}
      />
    </>
  );
}
